#  Run application tests, rubocop style checking, and brakeman security evaluation

image: ruby:2.7.4

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - bundler
            - yarn
          services:
            - postgres
          script:
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
                && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
                && apt-get update \
                && apt-get install -y google-chrome-stable --no-install-recommends
            - apt-get update && apt-get install -y nodejs npm && npm install -g yarn
            - cp config/database.ci.yml config/database.yml
            - bundle config set path vendor
            - bundle install
            - yarn install
            - RAILS_ENV=test bundle exec rails db:create
            - bundle exec rails test
            - bundle exec rails test:system
            - bundle exec rubocop
            - bundle exec brakeman

definitions:
  caches:
    bundler: ./vendor
    yarn: ./node_modules
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'cedar_admin_test'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
