#  Run application tests, rubocop style checking, and brakeman security evaluation

image: ruby:2.7.1

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - bundler
            - yarn
          services:
            - postgres
          script:
            - apt-get update && apt-get install -y nodejs npm && npm install -g yarn
            - cp config/database.ci.yml config/database.yml
            - bundle config set path vendor
            - bundle install
            - yarn install
            - export CEDAR_USPSTF_API_KEY=DUMMY-KEY
            - export CEDAR_CDS_CONNECT_BASIC_AUTH_USERNAME=DUMMY-KEY
            - export CEDAR_CDS_CONNECT_BASIC_AUTH_PASSWORD=DUMMY-KEY
            - export CEDAR_CDS_CONNECT_USERNAME=DUMMY-KEY
            - export CEDAR_CDS_CONNECT_PASSWORD=DUMMY-KEY
            - export CEDAR_CDS_CONNECT_BASE_URL=DUMMY-KEY
            - RAILS_ENV=test bundle exec rails db:create
            - bundle exec rake
            - bundle exec rubocop
            - bundle exec brakeman

definitions:
  caches:
    bundler: ./vendor
    yarn: ./node_modules
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'cedar_admin_test'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
