version: '3'
services:
  web:
    build: .
    env_file: .env
    command: ["bundle", "exec", "rails", "server", "--binding", "0.0.0.0"]
    ports:
      - "3000:3000"
  worker:
    build: .
    env_file: .env
    command: ["sh", "-c", "bundle exec whenever --update-crontab && cron -f -L15"]
